apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-dmp-twice"
  labels:
    dx.daocloud.io/service-name: dmp-twice
spec:
  replicas: {{ .Values.dmp.twice.replicas }}
  selector:
    matchLabels:
      dx.daocloud.io/service-name: dmp-twice
  template:
    metadata:
      labels:
        dx.daocloud.io/service-name: dmp-twice
    spec:
      containers:
        - image: {{ .Values.dmp.twice.image.repository }}:{{ .Values.dmp.twice.image.tag }}
          name: "{{ .Release.Name }}-dmp-twice"
          imagePullPolicy: {{ .Values.dmp.twice.image.pullPolicy }}
          livenessProbe:
            httpGet:
              path: /ping?full=1
              port: 8998
              scheme: HTTP
            initialDelaySeconds: 80
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /health?full=1
              port: 8998
              scheme: HTTP
            initialDelaySeconds: 95
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          resources:
            requests:
              memory: "2048Mi"
              cpu: "1000m"
            limits:
              memory: "2048Mi"
              cpu: "1000m"
          ports:
            - containerPort: 8765
              name: api
            - containerPort: 7000
              name: gateway
          envFrom:
            - configMapRef:
                name: "{{ .Release.Name }}-dmp-admin-configmap"
          volumeMounts:
            - name: host-time
              mountPath: /etc/localtime
              readOnly: true
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
